apiVersion: v1
kind: Pod
metadata:
  name: hasher
  labels:
    app: hasher
spec:
  containers:
  - name: hasher
    image: dockercoins/hasher:v0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80