apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "250Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379