apiVersion: v1
kind: Pod
metadata:
  name: rng
  labels:
    app: rng
spec:
  containers:
  - name: rng
    image: dockercoins/rng:v0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80