apiVersion: v1
kind: Pod
metadata:
  name: webui
  labels:
    app: webui
spec:
  containers:
  - name: webui
    image: dockercoins/webui:v0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80