apiVersion: v1
kind: Pod
metadata:
  name: worker
  labels:
    app: worker
spec:
  containers:
  - name: worker
    image: dockercoins/worker:v0.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"